services:
  database:
    image: postgres:latest
    container_name: ${CONTAINER_NAME} 
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}       
      POSTGRES_USER: ${DATABASE_USER}     
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}   
    volumes:
      - data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]  
      interval: 10s                          
      timeout: 5s                            
      retries: 5  

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: ${CONTAINER_NAME}
      DB_PORT: ${DATABASE_PORT}
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
                               
volumes:
  data:  